project:
  type: website

website:
  title: "chizo114.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: About 
      - text: EPPS6323
        menu: 
          - href: Assignment1.qmd
            text: Assignment1
          - href: Assignment2.qmd
            text: Assignment2
          - href: Assignment3.qmd
            text: Assignment3
          - href: Assignment4.qmd
            text: Assignment4
          - href: Assignment5.qmd
            text: Assignment5
          - href: Projectproposalpresentation.qmd
            text: Projectproposalpresentation 
     
      - text: EPPS6356
        menu:
          - href: value.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

